services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/project:rw
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: backend
    environment:
      PHP_IDE_CONFIG: serverName=backend
    volumes:
      - ./:/var/www/project:rw
